apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumbler-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: jumbler
          image: host.minikube.internal:5021/mglavitsch/jumblerb
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regsecret
