name: Build and deploy project jumbler-app-js

on:
  push:
    branches:
      - master
      
permissions:
  id-token: write
  contents: read

jobs:
  wf-jumbler-app-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.5.0'

      - name: Install dependencies
        run: |
          cd jumbler-app-js
          npm install

      - name: Build project
        run: |
          cd jumbler-app-js
          npm run build

      - name: Show GitHub Run ID
        run: |
          echo "Run ID: ${{ github.run_id }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}"
          role-session-name: "GitHubActions-${{ github.job }}-${{ github.run_id }}"
          role-duration-seconds: 900
          aws-region: eu-central-2

      - name: Deploy to S3
        run: |
          aws s3 rm s3://${{ secrets.AWS_BUCKET_NAME }}/ --recursive --region eu-central-2
          cd jumbler-app-js/dist
          HASHED_LICENSE_FILE=$(ls | grep -E '^THIRD-PARTY-LICENSES\.[a-f0-9]{8}\.txt$')
          aws s3 cp "$HASHED_LICENSE_FILE" s3://${{ secrets.AWS_BUCKET_NAME }}/ --cache-control "max-age=31536000, immutable" --region eu-central-2
          aws s3 cp bundle.*.js s3://${{ secrets.AWS_BUCKET_NAME }}/ --cache-control "max-age=31536000, immutable" --region eu-central-2
          aws s3 cp index.html s3://${{ secrets.AWS_BUCKET_NAME }}/index.html --cache-control "max-age=0, no-cache, no-store, must-revalidate" --region eu-central-2