name: Build and deploy project jumbler-app-js

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'jumbler-app-k8s/**'
      - 'jumbler-app-ts/**'
      - '**/*.md'
      - '**/LICENSE'
      - '**/page.png'
      
permissions:
  id-token: write
  contents: read

jobs:
  wf-jumbler-app-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.5.0'

      - name: Install dependencies
        run: |
          cd jumbler-app-js
          npm install

      - name: Build project
        run: |
          cd jumbler-app-js
          npm run build

      - name: Show GitHub Run ID
        run: |
          echo "Run ID: ${{ github.run_id }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}"
          role-session-name: "GitHubActions-${{ github.job }}-${{ github.run_id }}"
          role-duration-seconds: 900
          aws-region: eu-central-2

      - name: Deploy to S3
        run: |
          aws s3 rm s3://${{ secrets.AWS_BUCKET_NAME }}/ --recursive --region eu-central-2
          cd jumbler-app-js/dist
          HASHED_LICENSE_FILE=$(ls | grep -E '^THIRD-PARTY-LICENSES\.[a-f0-9]{16}\.txt$')
          HASHED_FAVICON_FILE=$(ls | grep -E '^favicon\.[a-f0-9]{16}\.ico$')
          HASHED_CHART_FILE=$(ls | grep -E '^AWS-services\.[a-f0-9]{16}\.svg$')
          HASHED_PORTRAIT_FILE=$(ls | grep -E '^portrait-mg\.[a-f0-9]{16}\.png$')
          aws s3 cp "$HASHED_LICENSE_FILE" s3://${{ secrets.AWS_BUCKET_NAME }}/ --content-type "text/plain" --cache-control "max-age=31536000, immutable" --region eu-central-2
          aws s3 cp "$HASHED_FAVICON_FILE" s3://${{ secrets.AWS_BUCKET_NAME }}/ --content-type "image/x-icon" --cache-control "max-age=31536000, immutable" --region eu-central-2
          aws s3 cp "$HASHED_CHART_FILE" s3://${{ secrets.AWS_BUCKET_NAME }}/ --content-type "image/svg+xml" --cache-control "max-age=31536000, immutable" --region eu-central-2
          aws s3 cp "$HASHED_PORTRAIT_FILE" s3://${{ secrets.AWS_BUCKET_NAME }}/ --content-type "image/png" --cache-control "max-age=31536000, immutable" --region eu-central-2
          aws s3 cp bundle.*.js s3://${{ secrets.AWS_BUCKET_NAME }}/ --content-type "application/javascript" --cache-control "max-age=31536000, immutable" --region eu-central-2
          aws s3 cp index.html s3://${{ secrets.AWS_BUCKET_NAME }}/index.html --content-type "text/html" --cache-control "max-age=0, no-cache, no-store, must-revalidate" --region eu-central-2
          aws s3 cp wrapper.html s3://${{ secrets.AWS_BUCKET_NAME }}/wrapper.html --content-type "text/html" --cache-control "max-age=0, no-cache, no-store, must-revalidate" --region eu-central-2
          aws s3 cp asset-manifest.json s3://${{ secrets.AWS_BUCKET_NAME }}/wrapper.html --content-type "application/json" --cache-control "max-age=0, no-cache, no-store, must-revalidate" --region eu-central-2
          aws s3 cp initial-text.txt s3://${{ secrets.AWS_BUCKET_NAME }}/initial-text.txt --content-type "text/plain" --cache-control "max-age=0, no-cache, no-store, must-revalidate" --region eu-central-2